### ISSUE TITLE
error popping up when trying to load any server through the launcher 

### ISSUE THREAD

**Issue by ronbrown553** [NFT-Worlds/NFT-Worlds-Game-Client#15]
Uncaught exception in thread "main"
net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: java.io.IOException: error reading C:\Users\Daddy\AppData\Roaming\.nftworlds\.minecraft\libraries\net\fabricmc\tiny-mappings-parser\0.3.0+build.17\tiny-mappings-parser-0.3.0+build.17.jar
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:213)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:172)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: error reading C:\Users\Daddy\AppData\Roaming\.nftworlds\.minecraft\libraries\net\fabricmc\tiny-mappings-parser\0.3.0+build.17\tiny-mappings-parser-0.3.0+build.17.jar
	at net.fabricmc.loader.impl.game.minecraft.LibClassifier.process(LibClassifier.java:88)
	at net.fabricmc.loader.impl.game.minecraft.LibClassifier.process(LibClassifier.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:184)
	... 4 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.LibClassifier.process(LibClassifier.java:72)
	... 6 more

**Comment by Jaxkr** [comment]
Thanks for your report, try removing your installation at %appdata%/.nftworlds and re-installing. This looks like your download was corrupted for some reason.

What version of Windows are you running?
