### ISSUE TITLE
Client stuck at 'Your NFT Worlds account is being set up'  (auth:login error)

### ISSUE THREAD

**Issue by blipn** [NFT-Worlds/NFT-Worlds-Game-Client#18]
Hello, i tried to reproduce the error i got with the exe, with the "yarn dev" script :
![image](https://user-images.githubusercontent.com/9851558/163784891-888acc5c-fa14-48da-8db2-e1efb3ca57c9.png)

```
┏ Main -----------------------

  ERROR in C:/Users/blipn/Downloads/NFT-Worlds-Game-Client-master/NFT-Worlds-Game-Client-master/node_modules/@types/react/index.d.ts(3121,14):
  TS2300: Duplicate identifier 'LibraryManagedAttributes'.

┗ ----------------------------
┏ Main -----------------------

  ERROR in C:/Users/blipn/Downloads/NFT-Worlds-Game-Client-master/NFT-Worlds-Game-Client-master/node_modules/@types/styled-components/node_modules/@types/react/index.d.ts(3103,14):
  TS2300: Duplicate identifier 'LibraryManagedAttributes'.

┗ ----------------------------
┏ Renderer -------------------

  ERROR in C:/Users/blipn/Downloads/NFT-Worlds-Game-Client-master/NFT-Worlds-Game-Client-master/node_modules/@types/react/index.d.ts(3121,14):
  TS2300: Duplicate identifier 'LibraryManagedAttributes'.

┗ ----------------------------
┏ Renderer -------------------

  ERROR in C:/Users/blipn/Downloads/NFT-Worlds-Game-Client-master/NFT-Worlds-Game-Client-master/node_modules/@types/styled-components/node_modules/@types/react/index.d.ts(3103,14):
  TS2300: Duplicate identifier 'LibraryManagedAttributes'.

┗ ----------------------------
┏ Electron -------------------

  10:58:01.087 > Error: Connection timeout
      at Timeout._onTimeout (C:\Users\blipn\Downloads\NFT-Worlds-Game-Client-master\NFT-Worlds-Game-Client-master\node_modules\crocket\lib\ipc.js:193:17)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

┗ ----------------------------
┏ Electron -------------------

  10:58:54.144 > Error occurred in handler for 'auth:login': {
    message: 'Request failed with status code 404',
    name: 'Error',
    stack: 'Error: Request failed with status code 404\n' +
      '    at createError (C:\\Users\\blipn\\Downloads\\NFT-Worlds-Game-Client-master\\NFT-Worlds-Game-Client-master\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n' +
      '    at settle (C:\\Users\\blipn\\Downloads\\NFT-Worlds-Game-Client-master\\NFT-Worlds-Game-Client-master\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n' +
      '    at IncomingMessage.handleStreamEnd (C:\\Users\\blipn\\Downloads\\NFT-Worlds-Game-Client-master\\NFT-Worlds-Game-Client-master\\node_modules\\axios\\lib\\adapters\\http.js:322:11)\n' +
      '    at IncomingMessage.emit (node:events:402:35)\n' +
      '    at endReadableNT (node:internal/streams/readable:1343:12)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
```

**Comment by blipn** [comment]
Ok i solved it by connecting one time to https://account.xbox.com/ to verify my account informations.

![image](https://user-images.githubusercontent.com/9851558/163787843-b9adca73-307f-4180-a28b-25df4c38a3fb.png)

**Comment by Jaxkr** [comment]
Thanks for the report. This appears to be occurring on Microsoft accounts that have never used Xbox Live before and don't own Minecraft: Java Edition.

**Comment by sonarmanic** [comment]
Did you connect to https://account.xbox.com/ in a browser? i tried this and im still unable to get past the issue?
